"use client";

import { useEffect, useState, useCallback } from "react";
import { FileText, Download, Plus, Info, Mail } from "lucide-react";

import SectionHeader from "../../components/ui/SectionHeader";
import EmptyState from "../../components/ui/EmptyState";
import ErrorState from "../../components/ui/ErrorState";
import { SkeletonTable } from "../../components/ui/LoadingSkeleton";
import { formatTunisDateTime, formatTunisDate } from "../../lib/time";

interface Report {
    report_id: string;
    area: string | null;
    report_type: string;
    minio_key: string;
    presigned_url: string;
    url_expires_at: string;
    metrics_summary: any;
    source_action_id: string | null;
    created_at: string;
}

export default function ReportsPage() {
    const [reports, setReports] = useState<Report[]>([]);
    const [loading, setLoading] = useState(true);
    const [creating, setCreating] = useState(false);
    const [error, setError] = useState<string | null>(null);
    const [areaInput, setAreaInput] = useState("ALL");
    const [emailMe, setEmailMe] = useState(true);
    const [lastResult, setLastResult] = useState<string | null>(null);

    const load = useCallback(async () => {
        setLoading(true);
        setError(null);
        try {
            const r = await fetch("/api/reports", { cache: "no-store" });
            if (!r.ok) throw new Error(`HTTP ${r.status}`);
            const json = await r.json();
            setReports(json.reports ?? []);
        } catch (e: any) {
            setError(String(e?.message ?? e));
        } finally {
            setLoading(false);
        }
    }, []);

    useEffect(() => { load(); }, [load]);

    const generate = async () => {
        setCreating(true);
        setLastResult(null);
        try {
            const res = await fetch("/api/reports", {
                method: "POST",
                headers: { "Content-Type": "application/json" },
                body: JSON.stringify({ area: areaInput || "ALL", email: emailMe }),
            });
            const json = await res.json().catch(() => ({}));
            if (json?.email) {
                const e = json.email;
                if (e.status === "sent") {
                    setLastResult(`PDF emailed to ${e.to} via ${e.provider}.`);
                } else if (e.status === "logged") {
                    setLastResult(`Email console-logged (SMTP not configured). To enable real send, set SMTP_* in .env.`);
                } else if (e.status === "skipped") {
                    setLastResult(`Email skipped: ${e.error}`);
                } else {
                    setLastResult(`Email failed: ${e.error ?? "no detail returned — check api-gateway logs"}`);
                }
            } else if (emailMe) {
                setLastResult("Email skipped — no recipient configured (set REPORT_RECIPIENT_EMAIL).");
            } else {
                setLastResult("PDF generated.");
            }
            await load();
        } catch (e: any) {
            setLastResult(`Generation failed: ${String(e?.message ?? e)}`);
        } finally {
            setCreating(false);
        }
    };

    return (
        <div style={{ padding: "24px 32px", display: "flex", flexDirection: "column", gap: 20 }}>
            <SectionHeader
                icon={FileText}
                title="Capacity Recommendation Reports"
                subtitle="PDF reports generated by pb-capacity-report. 7-day presigned URL. Email delivery optional."
                tone="default"
            />

            {/* What is a capacity report? — explainer card */}
            <div
                className="card"
                style={{
                    padding: 16,
                    background: "linear-gradient(135deg, rgba(168,85,247,0.08), rgba(139,92,246,0.02))",
                    border: "1px solid rgba(168,85,247,0.25)",
                }}
            >
                <div style={{ display: "flex", gap: 12, alignItems: "flex-start" }}>
                    <Info size={18} style={{ color: "#a855f7", flexShrink: 0, marginTop: 2 }} />
                    <div style={{ flex: 1 }}>
                        <div style={{ fontWeight: 700, color: "var(--text-primary)", marginBottom: 6 }}>
                            What is a Capacity Report?
                        </div>
                        <p style={{ margin: 0, fontSize: 12, lineHeight: 1.6, color: "var(--text-muted)" }}>
                            A PDF snapshot of the last 30 pipeline cycles for an area (or ALL). It covers
                            <strong> throughput / latency / packet-loss / active-users / anomaly count</strong>,
                            then derives capacity recommendations using the headroom formula
                            <code> (1 − avg / (peak × 1.3)) × 100</code> with thresholds at 60ms latency, 1% loss, and 5+ VAE anomalies/24h.
                        </p>
                        <ul style={{ margin: "8px 0 0 0", paddingLeft: 18, fontSize: 12, lineHeight: 1.6, color: "var(--text-muted)" }}>
                            <li><strong>Sections:</strong> Executive Summary · KPI History table · Recommendations · Methodology.</li>
                            <li><strong>Storage:</strong> MinIO bucket <code>reports/</code>, presigned URL valid <code>REPORTS_URL_TTL_SECONDS</code> (default 7 days).</li>
                            <li><strong>Email:</strong> Tick &quot;Email me a copy&quot; below to attach the PDF in an SMTP send to <code>REPORT_RECIPIENT_EMAIL</code>.
                                If SMTP not configured, audited as console-log in Notifications page.</li>
                        </ul>
                    </div>
                </div>
            </div>

            {/* Generate panel */}
            <div className="card card-compact" style={{ display: "flex", gap: 10, alignItems: "center", flexWrap: "wrap" }}>
                <label style={{ fontSize: 11, color: "var(--text-muted)", fontWeight: 600 }}>AREA:</label>
                <input
                    type="text"
                    placeholder="Area (or ALL)"
                    value={areaInput}
                    onChange={(e) => setAreaInput(e.target.value)}
                    style={{ padding: "6px 10px", fontSize: 12, background: "var(--bg-elevated)", border: "1px solid var(--border)", borderRadius: 6, color: "var(--text-primary)", width: 180 }}
                />
                <label
                    style={{ display: "inline-flex", gap: 6, alignItems: "center", fontSize: 12, color: "var(--text-primary)", cursor: "pointer" }}
                    title="Sends an SMTP email with the PDF attached to REPORT_RECIPIENT_EMAIL"
                >
                    <input type="checkbox" checked={emailMe} onChange={(e) => setEmailMe(e.target.checked)} />
                    <Mail size={12} />
                    Email me a copy
                </label>
                <button
                    className="l4-btn l4-btn-approve"
                    style={{ padding: "6px 14px", fontSize: 12, marginLeft: "auto" }}
                    disabled={creating}
                    onClick={generate}
                >
                    <Plus size={12} style={{ marginRight: 4 }} />
                    {creating ? "Generating…" : "Generate Report"}
                </button>
                {lastResult && (
                    <div
                        style={{
                            width: "100%",
                            fontSize: 11,
                            padding: "6px 10px",
                            borderRadius: 6,
                            background: lastResult.startsWith("Generation failed") || lastResult.startsWith("Email failed")
                                ? "rgba(239,68,68,0.1)"
                                : "rgba(34,197,94,0.08)",
                            color: lastResult.startsWith("Generation failed") || lastResult.startsWith("Email failed")
                                ? "var(--color-danger)"
                                : "var(--color-success)",
                            border: "1px solid rgba(255,255,255,0.05)",
                        }}
                    >
                        {lastResult}
                    </div>
                )}
            </div>

            {error && <ErrorState title="Failed to load reports" message={error} onRetry={load} />}
            {!error && loading && <SkeletonTable rows={6} />}

            {!error && !loading && reports.length === 0 && (
                <EmptyState
                    icon={FileText}
                    title="No reports yet"
                    description="Click 'Generate Report' above or run pb-capacity-report from the L4 Agent."
                />
            )}

            {!error && !loading && reports.length > 0 && (
                <div className="card">
                    <table className="table">
                        <thead>
                            <tr>
                                <th>Report ID</th>
                                <th>Area</th>
                                <th>Cycles</th>
                                <th>Anomalies (24h)</th>
                                <th>Created</th>
                                <th>Expires</th>
                                <th>Download</th>
                            </tr>
                        </thead>
                        <tbody>
                            {reports.map(r => (
                                <tr key={r.report_id}>
                                    <td className="mono" style={{ fontSize: 11 }}>{r.report_id}</td>
                                    <td className="mono">{r.area ?? "ALL"}</td>
                                    <td className="mono">{r.metrics_summary?.cycles_analyzed ?? "—"}</td>
                                    <td className="mono">{r.metrics_summary?.anomaly_count ?? r.metrics_summary?.anomaly_count_24h ?? "—"}</td>
                                    <td className="mono" style={{ fontSize: 11 }}>{formatTunisDateTime(r.created_at)}</td>
                                    <td className="mono" style={{ fontSize: 11 }}>{r.url_expires_at ? formatTunisDate(r.url_expires_at) : "—"}</td>
                                    <td>
                                        <a
                                            href={r.presigned_url}
                                            target="_blank"
                                            rel="noopener noreferrer"
                                            className="l4-btn l4-btn-approve"
                                            style={{ padding: "4px 10px", fontSize: 10, textDecoration: "none", display: "inline-flex", alignItems: "center", gap: 4 }}
                                        >
                                            <Download size={11} /> PDF
                                        </a>
                                    </td>
                                </tr>
                            ))}
                        </tbody>
                    </table>
                </div>
            )}
        </div>
    );
}
