-- Telecom Cloud Intelligence Platform (v1)
-- Postgres is the serving + metadata store, NOT the data lake.
-- Data lake lives in MinIO under raw/processed/curated.

BEGIN;

-- 1) Pipeline runs: traceability + reproducibility
CREATE TABLE IF NOT EXISTS pipeline_runs (
  id            BIGSERIAL PRIMARY KEY,
  run_id        TEXT NOT NULL UNIQUE,            -- UUID string generated by worker
  status        TEXT NOT NULL CHECK (status IN ('started','succeeded','failed')),
  started_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
  finished_at   TIMESTAMPTZ,
  error_message TEXT
);

-- 2) Dataset registry: pointers to MinIO objects + lineage to run
CREATE TABLE IF NOT EXISTS dataset_registry (
  id             BIGSERIAL PRIMARY KEY,
  run_id         TEXT NOT NULL REFERENCES pipeline_runs(run_id) ON DELETE CASCADE,
  dataset_type   TEXT NOT NULL,                  -- oss_kpi | bss_usage | joined_features | curated_insights
  layer          TEXT NOT NULL CHECK (layer IN ('raw','processed','curated')),
  format         TEXT NOT NULL,                  -- json | parquet | csv
  object_key     TEXT NOT NULL,                  -- MinIO key/path
  schema_version TEXT NOT NULL DEFAULT 'v1',
  row_count      BIGINT,
  created_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT uq_dataset UNIQUE (run_id, dataset_type, layer, object_key)
);

CREATE INDEX IF NOT EXISTS idx_dataset_registry_run ON dataset_registry(run_id);
CREATE INDEX IF NOT EXISTS idx_dataset_registry_layer_type ON dataset_registry(layer, dataset_type);

-- 3) Model registry: minimal governance
CREATE TABLE IF NOT EXISTS model_registry (
  id                 BIGSERIAL PRIMARY KEY,
  model_name         TEXT NOT NULL,              -- anomaly | sla-risk | correlation (optional)
  version            TEXT NOT NULL,
  artifact_object_key TEXT NOT NULL,             -- MinIO key/path for model artifact
  created_at         TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT uq_model UNIQUE (model_name, version)
);

-- 4) Anomalies: queryable AI outputs
CREATE TABLE IF NOT EXISTS anomalies (
  id             BIGSERIAL PRIMARY KEY,
  run_id         TEXT NOT NULL REFERENCES pipeline_runs(run_id) ON DELETE CASCADE,
  ts             TIMESTAMPTZ NOT NULL,
  region         TEXT NOT NULL,
  cell_id        TEXT NOT NULL,
  kpi_name       TEXT NOT NULL,                  -- latency_ms, packet_loss_pct, throughput_mbps, availability_pct
  severity       DOUBLE PRECISION NOT NULL CHECK (severity >= 0 AND severity <= 1),
  value          DOUBLE PRECISION NOT NULL,
  baseline_value DOUBLE PRECISION,
  model_name     TEXT DEFAULT 'anomaly',
  model_version  TEXT,
  created_at     TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_anomalies_run_ts ON anomalies(run_id, ts);
CREATE INDEX IF NOT EXISTS idx_anomalies_region_ts ON anomalies(region, ts);

-- 5) SLA risk scores: hero endpoint cache
CREATE TABLE IF NOT EXISTS sla_risk_scores (
  id            BIGSERIAL PRIMARY KEY,
  run_id        TEXT NOT NULL REFERENCES pipeline_runs(run_id) ON DELETE CASCADE,
  region        TEXT NOT NULL,
  window_start  TIMESTAMPTZ NOT NULL,
  window_end    TIMESTAMPTZ NOT NULL,
  score         DOUBLE PRECISION NOT NULL CHECK (score >= 0 AND score <= 1),
  explanation   JSONB,                            -- optional: top features, notes
  model_name    TEXT DEFAULT 'sla-risk',
  model_version TEXT,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_sla_risk_region_window ON sla_risk_scores(region, window_end DESC);

-- 6) Correlation insights: OSS <-> BSS business linkage
CREATE TABLE IF NOT EXISTS correlation_insights (
  id           BIGSERIAL PRIMARY KEY,
  run_id       TEXT NOT NULL REFERENCES pipeline_runs(run_id) ON DELETE CASCADE,
  region       TEXT NOT NULL,
  metric_x     TEXT NOT NULL,                    -- oss metric name
  metric_y     TEXT NOT NULL,                    -- bss metric name
  window_start TIMESTAMPTZ NOT NULL,
  window_end   TIMESTAMPTZ NOT NULL,
  method       TEXT NOT NULL DEFAULT 'pearson',   -- pearson | spearman
  corr_value   DOUBLE PRECISION NOT NULL CHECK (corr_value >= -1 AND corr_value <= 1),
  p_value      DOUBLE PRECISION,
  created_at   TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_corr_region_window ON correlation_insights(region, window_end DESC);

COMMIT;
